# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    push:
        branches: ["main", "staging"]
    pull_request:
        branches: ["main", "staging"]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: postgres:latest
                env:
                    POSTGRES_DB: ${{ secrets.DB_NAME }}
                    POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
                    POSTGRES_USER: ${{ secrets.DB_USER }}
                ports: ["5432:5432"]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Make .env
              run: printf "GIN_MODE=debug\nPROXY_1=localhost\nDB_HOST=localhost\nDB_USER=${{ secrets.DB_USER }}\nDB_PASS=${{ secrets.DB_PASS }}\nDB_NAME=${{ secrets.DB_NAME }}\nDB_PORT=5432\nDB_SSLMODE=disable\nDB_TIMEZONE=Asia/Jakarta" > .env

            - name: go get dependencies
              run: go get

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
